### ISSUE TITLE
Модальное окно

### ISSUE THREAD

**Issue by igosheva** [evdrug/burger#14]
Появление модального окна в целом сделано хорошо, что я бы рекомендовала тогда не все .modal-overlay раскрывать за счет scale(1), а только modal, а фон пусть появляется за счет прозрачности и например за счет изменения свойсва display. Т.е. фон изначально растянут на весь экран и плавно появляется, а можальное окно уже за счет scale

**Comment by evdrug** [comment]
не все так просто с scale, поэтому тоже плавно появляется))
