### ISSUE TITLE
Кнопка в header

### ISSUE THREAD

**Issue by igosheva** [evdrug/burger#3]
menu__order - не относится к тегу навигации. Нужно вынести ее из этого тега и просто обернуть навигацию и кнопку в div

**Comment by igosheva** [comment]
menu-nav__link-box - можно было сделать через псевдоэлемент)

**Comment by evdrug** [comment]
Кнопку вынес, хотя я подумал, что она подходит для навигации)))
menu-nav__link-box - я изначально вообще сделал через list-style, когда переделывал под sass, что-то решил блоком))

**Comment by evdrug** [comment]
menu-nav__link-box , понял про что ты)) сначала подумал о точках)
