### ISSUE TITLE
Нейминг не по БЭМ

### ISSUE THREAD

**Issue by igosheva** [evdrug/burger#6]
box-one__header - этот элемент относится к родителю с классом box-one, которого у тебя на странице нет. Но есть box__one. Надо бы переделать

**Comment by igosheva** [comment]
best-item__logo - тоже самое

**Comment by igosheva** [comment]
box-reviews__list - тоже самое. и внутри все классы такие же

**Comment by igosheva** [comment]
team__title - тоже самое

**Comment by igosheva** [comment]
box-menu__title-container - тоже самое

**Comment by igosheva** [comment]
box-maps__map - тоже самое

**Comment by igosheva** [comment]
social-list__item - тоже самое

**Comment by evdrug** [comment]
Фуууух, переписал)) Суть понял))
